name: Build and Push Docker Image

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  publish:
    uses: CSKU-Lab/.github/.github/workflows/docker-publish.yml@main
    with:
      image_name: web
      gitops_paths: apps/web/env.libsonnet
      service_name: web
    secrets: inherit
